pmu_ca:
  extraction_dest_relative_path: "pmu_ca/extracted/"
  transformation_dest_relative_path: "pmu_ca/transformed/"
  error_dest_relative_path: "pmu_ca/error/"
  loaded_dest_relative_path: "pmu_ca/loaded/"
  processed_dest_relative_path: "pmu_ca/processed/"
  file_downloaded_name: "Pmu_Senegal_ca_*csv"
  download_path: "K:/ETL/DATA_FICHIERS/pmu_ca/extracted/"
  ##### extraction config #####
  start_date: #2025-06-02
  end_date:  #2025-06-06
  wait_time: 200
  file_pattern: "Pmu_Senegal_ca_*csv"
  urls:
    login: "https://backoffice.pmu.sn/"
    report: "https://backoffice.pmu.sn/partner/view"

  html_elements:
    ### login page ###
    login_step1_xpath: "/html/body/jhi-main/div[1]/jhi-navbar/nav/div/ul/li[3]/a"
    login_step2_xpath: "/html/body/jhi-main/div[1]/jhi-navbar/nav/div/ul/li[3]/ul"
    username_element_xpath: "/html/body/ngb-modal-window/div/div/jhi-login-modal/div[2]/div/div[2]/form/div[1]/input"
    password_element_xpath: "/html/body/ngb-modal-window/div/div/jhi-login-modal/div[2]/div/div[2]/form/div[2]/input"
    login_submit_button_element_xpath: "/html/body/ngb-modal-window/div/div/jhi-login-modal/div[2]/div/div[2]/form/button"
    verification_xpath: "/html/body/jhi-main/div[1]/jhi-navbar/nav/div/ul/li[2]/a/span/span"

    ### report page ###
    date_month_element_xpath: "/html/body/jhi-main/div[2]/div/jhi-partner-view/div/div[2]/div[2]/div/div[2]/div[variable_to_be_set]"
    date_element_xpath: "/html/body/jhi-main/div[2]/div/jhi-partner-view/div/div[3]/div[2]/div/div/div[contains(., 'variable_to_be_set')]"
    step1_element_xpath: "/html/body/jhi-main/div[2]/div/jhi-partner-view/div/div[2]/div[1]/div/div[1]/span[contains(., 'variable_to_be_set')]"
    step2_element_xpath: "/html/body/jhi-main/div[2]/div/jhi-partner-view/div/div[2]/div[1]/div/div[2]/table"
    step3_element_xpath: "/html/body/jhi-main/div[2]/div/jhi-partner-view/div/div[3]/div[1]/div/div[2]/table"

  #### transform config ####
  files_to_transform_pattern: "*.csv"

  #### load config ####
  files_to_load_pattern: "*.csv"

#