sunubet_paiement:
  extraction_dest_relative_path: "sunubet_paiement/extracted/"
  transformation_dest_relative_path: "sunubet_paiement/transformed/"
  error_dest_relative_path: "sunubet_paiement/error/"
  loaded_dest_relative_path: "sunubet_paiement/loaded/"
  processed_dest_relative_path: "sunubet_paiement/processed/"
  file_downloaded_name: "*InstantGamesTransactionsHistory*csv"
  download_path: "K:/ETL/DATA_FICHIERS/sunubet_paiement/extracted/"
  ##### extraction config #####
  file_pattern: "*InstantGamesTransactionsHistory*csv"
  wait_time: 7000
  start_date: #2025-02-15
  end_date: #2025-02-17
  urls:
    login: "https://new-admin-sunubet.sporty-tech.net/"
    report: "https://new-admin-sunubet.sporty-tech.net/analysis/payments"
    report_history: "https://new-admin-sunubet.sporty-tech.net/reports/history"

  html_elements:
    ### login page ###
    username_element_xpath: "/html/body/hg-root/hg-login/div/div[2]/form/div[1]/input"
    password_element_xpath: "/html/body/hg-root/hg-login/div/div[2]/form/div[2]/input"
    login_submit_button_element_xpath: "/html/body/hg-root/hg-login/div/div[2]/form/div[3]/button"

    ### home ###
    verification_xpath: "/html/body/hg-root/hg-layout/div/div/hg-header/div/div/hg-topbar-infos/div/div[2]/div[2]"

    ### report generation page ###
    report_dropdown_xpath: "/html/body/hg-root/hg-layout/div/hg-sidebar/div[1]/div/ul/li[6]/a"
    report_paiement_xpath: "/html/body/hg-root/hg-layout/div/hg-sidebar/div[1]/div/ul/li[6]/ul/li[2]/a"
    calendar_xpath: "/html/body/hg-root/hg-layout/div/div/div/hg-payment-analysis/div[1]/div/form/hg-range/div/div/p-calendar/span/input"
    calendar_year_button_xpath: "/html/body/hg-root/hg-layout/div/div/div/hg-payment-analysis/div[1]/div/form/hg-range/div/div/p-calendar/span/div/div[1]/div/div[1]/div/button[2]"
    calendar_year_xpath: "/html/body/hg-root/hg-layout/div/div/div/hg-payment-analysis/div[1]/div/form/hg-range/div/div/p-calendar/span/div/div[2]/span"
    calendar_month_xpath: "/html/body/hg-root/hg-layout/div/div/div/hg-payment-analysis/div[1]/div/form/hg-range/div/div/p-calendar/span/div/div[2]/span"
    calendar_day_xpath: "/html/body/hg-root/hg-layout/div/div/div/hg-payment-analysis/div[1]/div/form/hg-range/div/div/p-calendar/span/div/div/div/div[2]/table/tbody/*/*/span[not(contains(@class, 'p-disabled'))]"
    fournisseur_dropdown_xpath: "/html/body/hg-root/hg-layout/div/div/div/hg-payment-analysis/div[1]/div/form/div[2]/hg-multi-select/ng-select/div/span"
    fournisseur_element_xpath: "/html/body/ng-dropdown-panel/div[2]/div[2]/div"
    search_button_xpath: "/html/body/hg-root/hg-layout/div/div/div/hg-payment-analysis/div[1]/div/form/div[3]/button[1]"
    nombre_depots_text_xpath: "//div[contains(@class, 'title') and starts-with(normalize-space(.), 'Nombre de dépôts')]/following-sibling::div[contains(@class, 'data')]"
    montant_depots_text_xpath: "//div[contains(@class, 'title') and starts-with(normalize-space(.), 'Montant des dépôts')]/following-sibling::hg-currency[contains(@class, 'data')]//div[contains(@class, 'value')]/span"
    nombre_retraits_text_xpath: "//div[contains(@class, 'title') and starts-with(normalize-space(.), 'Nombre de retraits')]/following-sibling::div[contains(@class, 'data')]"
    montant_retraits_text_xpath:  "//div[contains(@class, 'title') and starts-with(normalize-space(.), 'Montant des retraits')]/following-sibling::hg-currency[contains(@class, 'data')]//div[contains(@class, 'value')]/span"


#    dropdown_element_xpath: "/html/body/hg-root/hg-layout/div/div/div/hg-create-report/div/ngb-accordion/div[2]/div/button"
    report_verification_xpath: "/html/body/hg-root/hg-layout/div/hg-topbar/header/div/div[2]/div[5]/hg-profile-avatar/p-avatar/div/span"
    report_type_xpath: "/html/body/hg-root/hg-layout/div/div/div/hg-create-report/div/ngb-accordion/div[2]/div[2]/div/hg-create-report-button[2]/button"



    report_submit_button_xpath: "/html/body/ngb-popover-window/div[2]/hg-report-request-generator/form/button"

    ### report history page ###
    table_xpath: "//table/tbody"
    table_row_xpath: "//table/tbody/tr"
    download_button_xpath: "*/div/div/i"

  #### transform config ####
  files_to_transform_pattern: "*csv"

  #### load config ####
  files_to_load_pattern: "*.xlsx"

