solidicon:
  extraction_dest_relative_path: "solidicon/extracted/"
  transformation_dest_relative_path: "solidicon/transformed/"
  error_dest_relative_path: "solidicon/error/"
  loaded_dest_relative_path: "solidicon/loaded/"
  processed_dest_relative_path: "solidicon/processed/"
  file_downloaded_name: "Etat de la course*.xls"
  download_path: "K:/ETL/DATA_FICHIERS/solidicon/extracted/"
  ##### extraction config #####
  file_pattern: "Etat de la course*.xls"
  start_date: 2025-09-01 # defaut is today - 1 day
  end_date: 2025-09-30
  include_sup: false
  wait_time: 120
  urls:
    login: "http://soliditymanagement.mine.nu:86/SolidAdmin/Account/Login"
    report: "http://soliditymanagement.mine.nu:86/SolidReports/Reports#"

  html_elements:
    ### login page ###
    username_element_id: "UserName"
    password_element_id: "Password"
    login_submit_button_element_xpath: "/html/body/main/div/form/table/tbody/tr[4]/td/button"
    verification_xpath: "/html/body/header/div/div[4]/form/a[1]"

    ### report page ###
    start_date_day_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlDate"
    start_date_month_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlMonth"
    start_date_year_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlYear"
    end_date_day_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlDate"
    end_date_month_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlMonth"
    end_date_year_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlYear"
    submit_button_element_id: "OpsValidator_ContentPlaceHolder1_btnSubmit"
    download_button_element_id: "OpsValidator_ContentPlaceHolder1_btnExcel"
    error_message_element_xpath: "//span[contains(@id,'OpsValidator_ContentPlaceHolder1_lblErrInfo') and contains(text(),'Aucun enregistrement trouv')]"


  #### transform config ####
  files_to_transform_pattern: "solidicon*.xls"

  #### load config ####
  files_to_load_pattern: "solidicon*.csv"

