gitech:
  extraction_dest_relative_path: "gitech/extracted/"
  transformation_dest_relative_path: "gitech/transformed/"
  error_dest_relative_path: "gitech/error/"
  loaded_dest_relative_path: "gitech/loaded/"
  file_downloaded_name: "Etat de la course.xls"

  ##### extraction config #####
  urls:
    login: "https://www.pmuonline.sn/lonasemis/lonase_administration/Login.aspx"
    report: "https://www.pmuonline.sn/lonasemis/lonase_administration/HorseDrawWiseSales.aspx"

  html_elements:
    ### login page ###
    username_element_id: "Username"
    password_element_id: "Password"
    login_submit_button_element_id: "btnSubmit"
    verification_xpath: "/html/body/form/div[3]/table/tbody/tr/td/table[1]/tbody/tr[2]/td[3]/span"

    ### report page ###
    date_day_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlDate"
    date_month_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlMonth"
    date_year_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlYear"
    submit_button_element_id: "OpsValidator_ContentPlaceHolder1_btnSubmit"
    download_button_element_id: "OpsValidator_ContentPlaceHolder1_btnExcel"

  #### transform config ####

  #### load config ####
  files_to_load_pattern: "*.csv"

