gitech:
  # Chemins relatifs au DATA_PATH global du projet
  extraction_dest_relative_path: "gitech/extracted/"
  transformation_dest_relative_path: "gitech/transformed/"
  error_dest_relative_path: "gitech/error/"
  loaded_dest_relative_path: "gitech/loaded/"
  processed_dest_relative_path: "gitech/processed/"

  # Configuration pour l'extraction (BaseScrapper)
  download_path: "gitech/extracted/" # Sera résolu en chemin absolu. Utilisé par BaseScrapper pour configurer Chrome.
  # file_downloaded_name: "Etat de la course*.xls" # Optionnel, file_pattern est généralement suffisant.
  file_pattern: "Etat de la course*.xls" # Motif pour identifier le fichier téléchargé.
  wait_time: 120 # Temps d'attente max pour le téléchargement (secondes).

  # Dates pour l'extraction. Format YYYY-MM-DD.
  # Laisser vide pour que BaseScrapper utilise la veille par défaut, ou les variables d'env Jenkins.
  start_date: # 2025-03-01
  end_date: # 2025-03-04
  # include_sup: false # Non utilisé par BaseScrapper refactorisé.

  # Noms des variables d'environnement pour les dates (si fournies par Jenkins, par exemple)
  env_start_date_variable: "GITECH_START_DATE" # Exemple, à adapter aux noms réels utilisés par Jenkins
  env_end_date_variable: "GITECH_END_DATE"   # Exemple
  urls:
    login: "https://www.pmuonline.sn/lonasemis/lonase_administration/Login.aspx"
    report: "https://www.pmuonline.sn/lonasemis/lonase_administration/HorseDrawWiseSales.aspx"

  html_elements:
    ### login page ###
    username_element_id: "Username"
    password_element_id: "Password"
    login_submit_button_element_id: "btnSubmit"
    verification_xpath: "/html/body/form/div[3]/table/tbody/tr/td/table[1]/tbody/tr[2]/td[3]/span"

    ### report page ###
    start_date_day_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlDate"
    start_date_month_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlMonth"
    start_date_year_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlYear"
    end_date_day_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlDate"
    end_date_month_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlMonth"
    end_date_year_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlYear"
    submit_button_element_id: "OpsValidator_ContentPlaceHolder1_btnSubmit"
    download_button_element_id: "OpsValidator_ContentPlaceHolder1_btnExcel"
    error_message_element_xpath: "//span[contains(@id,'OpsValidator_ContentPlaceHolder1_lblErrInfo') and contains(text(),'Aucun enregistrement trouv')]"


  #### transform config ####
  files_to_transform_pattern: "gitech*.xls"

  #### load config ####
  files_to_load_pattern: "gitech*.csv"

