bwinner_gambie:
  extraction_dest_relative_path: "bwinner_gambie/extracted/"
  transformation_dest_relative_path: "bwinner_gambie/transformed/"
  error_dest_relative_path: "bwinner_gambie/error/"
  loaded_dest_relative_path: "bwinner_gambie/loaded/"
  processed_dest_relative_path: "bwinner_gambie/processed/"
  file_downloaded_name: "Recette paiement Journalier*.xls"
  download_path: "K:/ETL/DATA_FICHIERS/bwinner_gambie/extracted/"
  ##### extraction config #####
  file_pattern: "Recette paiement Journalier*.xls"
  start_date: #2025-06-02 # defaut is today - 1 day
  end_date: #2025-06-02
  include_sup: false
  wait_time: 30
  urls:
    login: "http://115.110.148.83/bwinnersmis/Administration/Login.aspx"
    report: "http://115.110.148.83/bwinnersmis/Administration/DatewisePa.aspx"

  html_elements:
    ### login page ###
    username_element_id: "Username"
    password_element_id: "Password"
    login_submit_button_element_id: "btnSubmit"
    verification_xpath: "/html/body/form/div[3]/table/tbody/tr/td/table[1]/tbody/tr[2]/td[3]/span"

    ### report page ###
    start_date_day_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlDate"
    start_date_month_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlMonth"
    start_date_year_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlYear"
    end_date_day_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlDate"
    end_date_month_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlMonth"
    end_date_year_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlYear"
    submit_button_element_id: "OpsValidator_ContentPlaceHolder1_btnSubmit"
    download_button_element_id: "OpsValidator_ContentPlaceHolder1_btnExcel"
    error_message_element_xpath: "//span[contains(@id,'OpsValidator_ContentPlaceHolder1_lblErrInfo') and contains(text(),'Aucun enregistrement trouv')]"

  #### transform config ####
  files_to_transform_pattern: "bwinner_gambie*.xls"

  #### load config ####
  files_to_load_pattern: "bwinner_gambie*.csv"

