bwinner:
  extraction_dest_relative_path: "afitech_daily_betting/processed/"
  #extraction_dest_relative_path: "bwinner/extracted/"
  transformation_dest_relative_path: "bwinner/transformed/"
  error_dest_relative_path: "bwinner/error/"
  loaded_dest_relative_path: "bwinner/loaded/"
  processed_dest_relative_path: "bwinner/processed/"
  file_downloaded_name: "Total Tax Report*.xlsx"
  #download_path: "K:/ETL/DATA_FICHIERS/bwinner/extracted/"
  download_path: "K:/ETL/DATA_FICHIERS/afitech_daily_betting/processed/"
  ##### extraction config #####
  file_pattern: "Total Tax Report*.xlsx"
  start_date: #2025-04-08
  end_date: #2025-03-04
  include_sup: false
  wait_time: 15
  urls:
    login: "https://a.bwinners.sn/oldbo/"
    report: "https://a.bwinners.sn/oldbo/Reports/TotalTaxReport"

  html_elements:
    ### login page ###
    username_element_xpath: "/html/body/form/fieldset/input[1]"
    password_element_xpath: "/html/body/form/fieldset/input[2]"
    login_submit_button_element_id: "submit"
    verification_xpath: "/html/body/form/div[3]/table/tbody/tr/td/table[1]/tbody/tr[2]/td[3]/span"

    ### report page ###
    actionone_element_xpath: "/html/body/div[5]/section/div[3]/div[2]/span[1]/span/span/span[1]"
    actiontwo_element_xpath: "/html/body/div[7]/div/ul/li[3]"
    actionthree_element_xpath: "/html/body/div[5]/section/div[2]/span[1]/span/span[1]"
    actionfour_element_xpath: "/html/body/div[11]/div/ul/li[1]"

    from_date_element_id: "FromDate"
    to_date_element_id: "ToDate"
    filter_button_element_id: "btnFilter"
    download_button_element_xpath : "/html/body/div[5]/section/div[3]/div[1]/div/a"

  #### transform config ####
  transformed_start_date: #2025-06-02
  transformed_end_date: #2025-06-02
  files_to_transform_pattern: "*.xlsx"

  #### load config ####
  files_to_load_pattern: "bwinner_transformed*.csv"

