editec_lotto_final:
  extraction_dest_relative_path: "editec_lotto_final/extracted/"
  transformation_dest_relative_path: "editec_lotto_final/transformed/"
  error_dest_relative_path: "editec_lotto_final/error/"
  loaded_dest_relative_path: "editec_lotto_final/loaded/"
  processed_dest_relative_path: "editec_lotto_final/processed/"
  file_downloaded_name: "Recette paiement Journalier*.xls"
  download_path: "K:/ETL/DATA_FICHIERS/editec_lotto_final/extracted/"
  ##### extraction config #####
  file_pattern: "Recette paiement Journalier*.xls"
  start_date: 2025-11-16
  end_date: 2025-11-16
  include_sup: false
  wait_time: 400
  urls:
    login: "https://www.pmuonline.sn/lonasemis/lonase_administration/Login.aspx"
    report: "https://www.pmuonline.sn/lonasemis/lonase_administration/DatewisePa.aspx"

  html_elements:
    ### login page ###
    username_element_id: "Username"
    password_element_id: "Password"
    login_submit_button_element_id: "btnSubmit"
    verification_xpath: "/html/body/form/div[3]/table/tbody/tr/td/table[1]/tbody/tr[2]/td[3]/span"

    ### report page ###
    start_date_day_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlDate"
    start_date_month_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlMonth"
    start_date_year_element_id: "OpsValidator_ContentPlaceHolder1_FDate_ddlYear"
    end_date_day_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlDate"
    end_date_month_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlMonth"
    end_date_year_element_id: "OpsValidator_ContentPlaceHolder1_TDate_ddlYear"

    # product input #
    product_select_element_id: "OpsValidator_ContentPlaceHolder1_DDlGameType"
    product_item_element_value: "4"

    submit_button_element_id: "OpsValidator_ContentPlaceHolder1_btnSubmit"
    download_button_element_id: "OpsValidator_ContentPlaceHolder1_btnExcel"
    download_button_element_xpath: "/html/body/form/div[3]/table[8]/tbody/tr/td/div/table[1]/tbody/tr/td/input[2]"
    error_message_element_xpath: "//span[contains(@id,'OpsValidator_ContentPlaceHolder1_lblErrInfo') and contains(text(),'Aucun enregistrement trouv')]"


  #### transform config ####
  files_to_transform_pattern: "editec_lotto_final*.xls"

  #### load config ####
  files_to_load_pattern: "editec_lotto_final*.csv"

